version: '3.7'
services:

  pf-mail:
    container_name: dovecot-mail
    image: reluparfene/fd-mail-dovecot
    ports:
      - "24:24"
      - "143:143"
    volumes:
      - /home/vmail:/home/vmail
      - pf-auth:/home/postfix
    environment:
    - LDAP_HOST=172.30.10.1
    - LDAP_BASE=dc=noit,dc=ro
    - LDAP_ADMIN=cn=admin,dc=noit,dc=ro
    - LDAP_PASS=1q2w3e4r
    logging:
      driver: syslog

    networks:
    - fusion-izit
    restart: always

volumes:
  pf-auth:
    driver: local

networks:
  fusion-izit:
