version: '3.7'
services:

  fd-mail-openldap:
    container_name: fd-mail-ldap
    image: ldap-init
    ports:
      - 389:389
      #- 636:636
#    volumes:
#      - data:/var/lib/ldap
#      - config:/etc/openldap/slapd.d
#      - certs:/etc/openldap/certs

    networks:
    - fusion-izit
    restart: always

#volumes:
#  data:
#    driver: local
#  config:
#    driver: local
#  certs:
#    driver: local

networks:
  fusion-izit:
