version: '3.7'
services:

  fusiondirectory-app:
    container_name: fusiondirectory-izit
    image: reluparfene/fusiondirectory:1.3.1
    ports:
      - 5202:80
    volumes:
    - ./logs:/www/logs
    environment:
    - LDAP_HOST=127.0.0.1
    - LDAP_BASE=dc=noit,dc=ro
    - LDAP_ADMIN_PASS=1q2w3e4r
    - SITE=Default SITE

    - LDAP1_HOST=fusiondirectory-openldap-izit
    - LDAP1_BASE_DN=dc=noit,dc=ro
    - LDAP1_ADMIN_DN=cn=admin,dc=noit,dc=ro
    - LDAP1_ADMIN_PASS=1q2w3e$$R
    - LDAP1_PORT=389
    - LDAP1_NAME=IZIT Fusion Directory

    #- LDAP2_BASE_DN=dc=example,dc=org
    #- LDAP2_ADMIN_DN=cn=admin,dc=example,dc=org
    #- LDAP2_HOST=openldap-fusiondirectory2
    #- LDAP2_ADMIN_PASS=password2
    #- LDAP2_NAME=Development
    #- LDAP2_TLS=TRUE
    networks:
    - fusion-izit
    restart: always

networks:
  fusion-izit:
    external: true
