version: '3.7'
services:

  fd-mail:
    container_name: fd-mail
    image: reluparfene/fd-mail:1.3.1
    ports:
      - 5202:80
    environment:
    - LDAP_HOST=fd-mail-ldap
    - LDAP_BASE=dc=noit,dc=ro
    - LDAP_ADMIN_PASS=1q2w3e4r
    - SITE=Default SITE

    networks:
    - fusion-izit
    restart: always

networks:
  fusion-izit:
