version: '3.7'
services:

  fd-mail:
    container_name: fd-web-finexcont
    image: reluparfene/fd-mail:1.3.1
    ports:
      - 5202:80
    environment:
    - LDAP_HOST=fd-ldap-finexcont
    - LDAP_BASE=dc=noit,dc=ro
    - LDAP_ADMIN_PASS=1q2w3e4r
    - SITE=FINEXCONT
    - SENDMAIL_HOST=172.30.10.1
    logging:
      driver: syslog
    depends_on:
    -  fd-mail-ldap
    networks:
      fusion-izit:
        ipv4_address: 192.168.30.20
    restart: always

  fd-mail-ldap:
    container_name: fd-ldap-finexcont
    image: reluparfene/fd-mail-ldap:1.3.1
    ports:
      - 389:389
      #- 636:636
    volumes:
      - data:/var/lib/ldap
      - config:/etc/openldap/slapd.d
      - certs:/etc/openldap/certs

    networks:
      fusion-izit:
        ipv4_address: 192.168.30.30
    restart: always

volumes:
  data:
    driver: local
  config:
    driver: local
  certs:
    driver: local

networks:
  fusion-izit:
    ipam:
      config:
        - subnet: "192.168.30.0/24"
