version: '3.8'
services:

  fd-mail:
    container_name: fusiondirectory
    image: reluparfene/fusiondirectory:1.3.1
    ports:
      - 5202:80
    environment:
    - LDAP_HOST=fd-mail-ldap
    - LDAP_BASE=dc=noit,dc=ro
    - LDAP_ADMIN=cn=admin,dc=noit,dc=ro
    - LDAP_PASS=1q2w3e4r
    - SITE=Default SITE

    networks:
    - fusion-izit
    restart: always

networks:
  fusiondirectory:
    external: true
