version: '3.7'
services:

  postfix:
    container_name: postfix-mail
    image: pf-init
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /dev/log:/dev/log
      - /etc/pki/tls/certs:/etc/postfix/certs:ro
      - /etc/pki/tls/private:/etc/postfix/private:ro
      - pf-auth:/var/spool/postfix/private/dovecot
    environment:
    - LDAP_HOST=172.30.1.75
    - LDAP_BASE=dc=mail-domains,dc=noit,dc=ro
    - LDAP_ADMIN=cn=admin,dc=noit,dc=ro
    - LDAP_PASS=1q2w3e4r
    - LMTP_HOST=172.30.1.75
    - CERT=mail.stroici.ro.pem
    - KEY=mail.stroici.ro-key.pem
    - CA=mail.stroici.ro-ca.pem
    logging:
      driver: syslog

    networks:
    - fusion-izit
    restart: always

volumes:
  pf-auth:
    driver: local

networks:
  fusion-izit:
